### ISSUE TITLE
Feed entries have incorrect URL

### ISSUE THREAD

**Issue by gemmaro** [rsmp-nordic/rsmp_website#50]
Hello,

Currently the feed entries have URL whose host part is `github.com`.  For example, <https://rsmp-nordic.org/feed.xml> has the blog post URL https://*github.com*/2023/09/22/rsmp-core-and-sxl-updates.html, but it should be https://*rsmp-nordic.org*/2023/09/22/rsmp-core-and-sxl-updates.html.

I wonder if simply setting `url` to `https://rsmp-nordic.org` fixes this problem ([commit][]), while [the generated feed][feed] has extra prefixes like https\://rsmp-nordic.org/*rsmp_website*/2023/09/22/rsmp-core-and-sxl-updates.html.

References:

* [Jekyll Feed plugin - Optional configuration options][feed]
* [Jekyll - Permalinks - Built-in formats][permalink]

[feed]: https://gemmaro.github.io/rsmp_website/feed.xml
[commit]: https://github.com/gemmaro/rsmp_website/commit/a9a456fb13c8badfbe9a620e3fa2a6ce9cb8a861
[permalink]: https://jekyllrb.com/docs/permalinks/#built-in-formats
[feed]: https://github.com/jekyll/jekyll-feed#optional-configuration-options

**Comment by emiltin** [comment]
Thank you for reporting this!

**Comment by emiltin** [comment]
hi @gemmaro, i set the url in the jekyll config, and this make the feed work. i was a bit worried that it would cause problems with links, but it seems to work.

however, there's an issue with images. i think this is because we're using a custom front matter for images that includes info about attribution and license, eg:

```yaml
---
layout: post
title:  "RSMP for Bus Priority"
date:   2020-08-12
image:
  url: /assets/images/busses_magasin.jpg
  attribution: Jacob Surland
  license:
    description: CC BY-NC-ND 2.0
    url: https://creativecommons.org/licenses/by-nc-nd/2.0/
---
```

i seems the feed gem reads the image config see:
https://github.com/jekyll/jekyll-feed#optional-configuration-options

so it up generating corrupted image urls like:
`url="https://rsmp-nordic.org/%7B%22url%22=%3E%22/assets/images/busses_magasin.jpg%22,%20%22attribution%22=%3E%22Jacob%20Surland%22,%20%22license%22=%3E%7B%22description%22=%3E%22CC%20BY-NC-ND%202.0%22,%20%22url%22=%3E%22https://creativecommons.org/licenses/by-nc-nd/2.0/%22%7D%7D"`

i think this can be fixed by placing just the url in the `image` tag:

```yaml
---
layout: post
title:  "RSMP for Bus Priority"
date:   2020-08-12
image: /assets/images/busses_magasin.jpg
image_attribution: Jacob Surland
image_license:
    description: CC BY-NC-ND 2.0
    url: https://creativecommons.org/licenses/by-nc-nd/2.0/
---
```

and change includes/_image.html accordingly.
